version: '3'

services:

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: edumgtk2020/node-home-lib-service-app:latest  
    restart: unless-stopped
    env_file: .env  
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src  
    networks:
      - app-network
    depends_on:
      - db  

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    image: edumgtk2020/node-home-lib-service-db:latest  
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  db-ui:
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: "edu@544062.ru"
      PGADMIN_DEFAULT_PASSWORD: "edumgtk2020"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - app-network  

volumes:
  postgres_data:    
  pgadmin_data:

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"