version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: edumgtk2020/node-home-lib-service-app:latest  
    restart: unless-stopped
    env_file: .env  
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src  
