version: '3'

services:
  app:
    # image: edumgtk2020/app
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    restart: always
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
    networks:
      app-network:
    depends_on:
      - db

  db:
    # image: edumgtk2020/db
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - data:/var/lib/postgresql/data
      - logs:/logs
    command: postgres -p $POSTGRES_PORT -c logging_collector=$POSTGRES_LOG -c log_directory=$POSTGRES_LOG_DIR -c log_min_messages=$POSTGRES_LOG_LEVEL
    
    networks:
      app-network:

volumes:
  data:
    name: data
  logs:
    name: logs

networks:
  app-network:
    name: intra
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          ip_range: ${NETWORK_IP_RANGE}
          gateway: ${NETWORK_GATEWAY}
