version: '3'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: app
    restart: unless-stopped
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    networks:
      app-network:
        ipv4_address: 192.168.100.100
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    restart: unless-stopped
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      app-network:
        ipv4_address: 192.168.100.101

volumes:
  postgres:
    name: data

networks:
  app-network:
    name: intra
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
          ip_range: 192.168.100.0/24
          gateway: 192.168.100.1
